module MyGame {

    export const Drugs: string[] = [
        'Crotosine',
        'Prepur',
        'Nutrogestin',
        'Ultripirin',
        'Antivate',
        'Nitrozole',
        'Abfine',
        'Asparaletra',
        'Ramipirone',
        'Brimomune',
        'Abiracline',
        'Calciunonide',
        'Ambebazine',
        'Aldebyclor',
        'Interdeine',
        'Subostadil',
        'Abotasol',
        'Pulmomulin',
        'Megatestryl',
        'Ciclopenem',
        'Valzide',
        'Entraretin',
        'Edrotamine',
        'Bacteriranon',
        'Micronized',
        'Diazenone',
        'Ombidarone',
        'Ampitant',
        'Clinitora',
        'Roxarelin',
        'Victoracil',
        'Dapfergen',
        'Adalariva',
        'Benesol',
        'Bonirabine',
        'Abcelex',
        'Bacteprotin',
        'Tramaban',
        'Roxanuma',
        'Omedeine',
        'Lysovax',
    ];

}